### ISSUE TITLE
Getting an OAuth2 Error. Really hoping to get this to work.

### ISSUE THREAD

**Issue by Rayn1022** [bvulaj/blink1-discord#1]
Error: OAuth2 Error: invalid_scope: The requested scope is invalid, unknown, or malformed.
    at RPCClient._onRpcMessage (C:\Users\Administrator\Documents\GitHub\blink1-discord\node_modules\discord-rpc\src\client.js:185:19)
    at IPCTransport.emit (node:events:390:28)
    at C:\Users\Administrator\Documents\GitHub\blink1-discord\node_modules\discord-rpc\src\transports\ipc.js:134:18
    at decode (C:\Users\Administrator\Documents\GitHub\blink1-discord\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\blink1-discord\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (node:events:390:28)
    at emitReadable_ (node:internal/streams/readable:578:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 5000,
  data: {
    code: 5000,
    message: 'OAuth2 Error: invalid_scope: The requested scope is invalid, unknown, or malformed.'
  }
}

Any ideas?

**Comment by AlexVulaj** [comment]
The readme changes proposed here should help you out
https://github.com/bvulaj/blink1-discord/pull/2
